#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

old_untracked=$(git status --porcelain | grep " M" | sed 's/ M //g')

yarn lint

new_untracked=$(git status --porcelain | grep " M" | sed 's/ M //g')

for newFile in $new_untracked; do
  match=false
  for oldFile in $old_untracked; do
    if [ $oldFile = $newFile ]; then
      match=true
      break
    fi
  done

  if [ $match = false ] ; then
    printf "${GREEN}Adding lint formatting changes: $newFile\n${NC}"
    git add $newFile
  fi
done